version: '3.3'
services:
  wireguard:
    build: .
    cap_add:
     - NET_ADMIN
    volumes:
     - /dev/net/tun:/dev/net/tun
     - ./wireguard:/etc/wireguard
    environment:
     - WG_COLOR_MODE=always
     - LOG_LEVEL=info
     - PORT=5000
     - SERVER=10.99.0.2:3004
    ports:
     - 51820:51820/udp
     - 0.0.0.0:5000:5000
    restart: always
