#   proxy:
#     build: .
#     container_name: proxy
#     network_mode: host
#     environment:
#       - PORT=3005
#       - SERVER=192.168.64.3:3002
#     volumes:
#       - ./entrypoint.sh:/entrypoint.sh
#       - ./wg0.conf:/etc/wireguard/wg0.conf
#       - ./boringtun-cli:/usr/local/bin/boringtun
#     cap_add:
#       - NET_ADMIN
#       - SYS_MODULE

version: '3.3'
services:
  wireguard:
    build: .
    cap_add:
     - NET_ADMIN
    sysctls:
     - net.ipv4.ip_forward=1
    volumes:
     - /dev/net/tun:/dev/net/tun
     # Folder with 'publickey', 'privatekey' and 'wg0.conf'
     - ./wireguard:/etc/wireguard
    environment:
     - WG_COLOR_MODE=always
     - LOG_LEVEL=info
     - PORT=5000
     - SERVER=10.99.0.2:3004
    ports:
     - 51820:51820/udp
     - 0.0.0.0:5000:5000
    # Uncomment the following line when 'AllowedIPs' is '0.0.0.0/0'
    # privileged: true
    restart: always
